version: "3.8"
services:
  favorites_container:
    container_name: favorites_container
    build: ./
    command: ./wait-for-db.sh ./favorites_service "migrate"
    environment:
      - DSN=${DSN}
      # - POSTGRES_HOST=go_shop_postgres
      # - POSTGRES_USER=${POSTGRES_USER}
      # - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # - POSTGRES_DB=${POSTGRES_DB}
      # - POSTGRES_PORT=5432
      #- KAFKA_BROKER=kafka:9092
    networks:
      - shopongo_default
    ports:
      - "8083:8083"


networks:
  shopongo_default:
    external: true
